### PR TITLE
change "Tube Archivist IP" to "Tube Archivist URL"

### PR DESCRIPTION
**Pull request by bakkot**
Saying "IP" is confusing when a.) it can be a domain name, not an IP and b.) it's supposed to include the HTTP part, not just a bare IP. (It's also documented as "URL" in the readme.)

Honestly it's a bit weird to have the protocol and domain in one place and the port in a different field. Is there a reason not to just have one field that expects something like `http://tubearchivist.local:8000`, i.e. a full URL as you'd have in the browser? I can make that change instead if you'd prefer.

### CODE REVIEW

**Comment by bbilly1** [comment]
Yeah, that would make more sense, to have it all in one text field, so you could also easily omit the port if you have a reverse proxy for example and running this on port 80 already.

But I think that will break the existing connection details though? After updating the extension, folks would have to enter their full URL? Well, I guess, with the connection test function, it would be obvious that there is no connection any more.

Also would make the form smaller... So I'd say with the addition to now being able to build links with the observer (thanks for that!), let's call this a breaking change and make a bigger version bump with all these improvements.

**Comment by bakkot** [comment]
It should be easy enough to derive out the full URL-with-port from the existing parts; no reason it needs to be a breaking change. Just take what would currently go in two textboxes and combine it into one.

**Comment by bbilly1** [comment]
that's true, and if no port, default to `80`. And if no protocol, inject `http://` automatically, for conveniently dealing with #5?

**Comment by bbilly1** [comment]
@bakkot What do you think? Do you want to look into this, to join the port button into the same field? Then we can wrap this up soon. I've pushed my changes to the master branch.

**Comment by bakkot** [comment]
@bbilly1 Done. Testing locally seems to work. And as mentioned above I've kept the old format for the internal storage, so it shouldn't break anything.

**Comment by bakkot** [comment]
Lol, sorry, thought I had. I also rebased on master so it's up-to-date.

**Pull request merged**
