### PR TITLE
Stop click propagating to elements behind download/subscribe buttons

### LINKED ISSUE #39: Tapping the download icon shouldn't open up video uploader's channel page in new YT redesign
Hi. I noticed this problem in the new YouTube redesign, where tapping the TA download button also seems to open up the video uploader's channel page (besides correctly downloading the video).

image

### PR DESCRIPTION
**Pull request by ritiek**
Fixes #39.

### CODE REVIEW

**Comment by bbilly1** [comment]
Interesting, new YT design, I haven't encountered this, at least so far. 

I remember dealing with a similar problem with the little video button, but I didn't encounter the same problem on the channel button.

Anyway to force a change to test the new design so I can test this?

But then again, I don't see why this would cause a problem, as we wouldn't want to bubble up the event anyways.

**Comment by ritiek** [comment]
I see, not sure how it works.

I was being treated with the new redesign here in India when browsing YouTube logged in through my Google account. I don't see it in incognito. Interestingly, I also don't see it now anymore after I logged out and logged in back into my Google account.

**Comment by Ogglord** [comment]
Google is probably rolling out new designs for YT in specific regions, limited testing + limited risk.

**Comment by bbilly1** [comment]
ok, let's go ahead with this, then if they ever roll this out, we are ready.

**Pull request merged**
