### PR TITLE
Add compatibility with DeArrow

### LINKED ISSUE #33: When used in combination with DeArrow (crowdsourced titles), many titles just show up blank.
It's always a little awkward when two separate projects conflict like this, but I figured I'd raise an issue here. The relatively new extension DeArrow replaces clickbait video titles with crowdsourced improvements, and it has really improved the ergonomics of the site (maybe worth integrating with TA like Sponsorblock, but I digress...). Unfortunately, when both DeArrow and the TA extension are used at the same time and I visit a list of videos (subscriptions, channel), any video without a crowdsourced title improvement shows up with a blank title, i.e. 
image

Perhaps one way to avoid needing close coordination between these two projects would be to make certain DOM modifications able to be disabled in the TA extension. I mostly use it to sync the cookie and on individual video pages, both of which work great today.

### PR DESCRIPTION
**Pull request by farcaller**
Fixes #33, works around the issues in #34.

This basically moves the injected button higher the DOM so it doesn't clash with dearrow. Verified with dearrow both missing and present.

### CODE REVIEW

**Comment by bbilly1** [comment]
Thanks for taking a look at this. I merged the fix from #35 also pushed some changes for the channel button selector, YT likes to move things around from time to time, requiring this extension to update. 

Please merge master into your branch and fix the conflict.

**Comment by farcaller** [comment]
Rebased, cleaned up, verified still functional 👍

**Comment by Iliannnn** [comment]
Tested it, and it's working as expected. Even on Firefox, thanks for this fix @farcaller! Hopefully this gets merged & released soon :)

**Comment by Iliannnn** [comment]
Nevermind, still bugged with DeArrow. Titles dissapearing (1), other weird bugs when unhiding modified title (2 & 3).

image
image
image

**Comment by farcaller** [comment]
Are you sure that's on the rebased version? Because I specifically worked around this issue:

image

And I'd be very curious to see the DOM that caused it.

FWIW, I've been running the patched version from this PR for 4 days with zero issues.

**Comment by Iliannnn** [comment]
> Are you sure that's on the rebased version? Because I specifically worked around this issue:
> 
> image
> 
> And I'd be very curious to see the DOM that caused it.
> 
> FWIW, I've been running the patched version from this PR for 4 days with zero issues.

I must installed it wrong to my browser then. Any pointers how you're doing this?

**Comment by farcaller** [comment]
> I must installed it wrong to my browser then. Any pointers how you're doing this?

Download the zip from my branch (e.g. https://github.com/farcaller/tubearchivist-browser-extension/archive/refs/heads/dearrow.zip), unzip it, rename either `manifest-chrome.json` or `manifest-firefox.json` to just `manifest.json`, and use the load unpacked installation method for your browser. Be sure to uninstall the official one. You'll need to provide the credentials again in the unpacked version.

**Comment by Iliannnn** [comment]
> > I must installed it wrong to my browser then. Any pointers how you're doing this?
> 
> Download the zip from my branch (e.g. https://github.com/farcaller/tubearchivist-browser-extension/archive/refs/heads/dearrow.zip), unzip it, rename either `manifest-chrome.json` or `manifest-firefox.json` to just `manifest.json`, and use the load unpacked installation method for your browser. Be sure to uninstall the official one. You'll need to provide the credentials again in the unpacked version.

That fixed it. I don't know what happend last time I installed it, but now it's working perfectly. Thanks!

**Comment by bbilly1** [comment]
Nice, thanks for implementing this.

**Pull request merged**
